/**
 * Minimal YAML-frontmatter renderer for the vault (see materialize-note).
 * Deliberately tiny — this only ever needs to emit the handful of scalar/array
 * property shapes OSLIFE's own notes use, not general-purpose YAML. Null/
 * undefined/empty-array values are omitted entirely rather than emitted as
 * `null`, so files stay close to how a human would actually write frontmatter.
 */

export type FrontmatterValue = string | number | boolean | string[] | null | undefined;
export type Frontmatter = Record<string, FrontmatterValue>;

function scalar(v: string | number | boolean): string {
  if (typeof v !== "string") return String(v);
  // Quote anything that would otherwise confuse a YAML parser (colons, quotes,
  // leading/trailing whitespace, or a value that merely looks numeric/boolean).
  const needsQuoting = /[:#'"[\]{}]|^\s|\s$|^$/.test(v) || /^(true|false|null|\d)/i.test(v);
  return needsQuoting ? `"${v.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"` : v;
}

function render(fm: Frontmatter): string {
  const lines: string[] = [];
  for (const [key, value] of Object.entries(fm)) {
    if (value === null || value === undefined) continue;
    if (Array.isArray(value)) {
      if (!value.length) continue;
      lines.push(`${key}: [${value.map((v) => scalar(v)).join(", ")}]`);
    } else {
      lines.push(`${key}: ${scalar(value)}`);
    }
  }
  return lines.join("\n");
}

/** Render a full note: `---\nfrontmatter\n---\n\nbody`. */
export function renderNote(frontmatter: Frontmatter, body: string): string {
  return `---\n${render(frontmatter)}\n---\n\n${body.trim()}\n`;
}

/**
 * The read-direction counterpart to renderNote() — for notes written BY HAND
 * in Obsidian (vault-inbox-sync) rather than generated by OSLIFE. Deliberately
 * as small as the renderer: only scalar/array values, no nested maps, no
 * multi-line strings. A file with no `---` frontmatter block at all (or a
 * malformed one) just returns the whole file as `body` with `{}` — this must
 * never throw on a plain human-written Markdown file.
 */
export function parseFrontmatter(raw: string): { frontmatter: Record<string, string | string[]>; body: string } {
  const m = raw.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n?([\s\S]*)$/);
  if (!m) return { frontmatter: {}, body: raw.trim() };

  const frontmatter: Record<string, string | string[]> = {};
  for (const line of m[1].split(/\r?\n/)) {
    const kv = line.match(/^([A-Za-z0-9_-]+):\s*(.*)$/);
    if (!kv) continue;
    const [, key, rawValue] = kv;
    const value = rawValue.trim();
    if (value.startsWith("[") && value.endsWith("]")) {
      frontmatter[key] = value
        .slice(1, -1)
        .split(",")
        .map((v) => v.trim().replace(/^"(.*)"$/, "$1"))
        .filter(Boolean);
    } else {
      frontmatter[key] = value.replace(/^"(.*)"$/, "$1");
    }
  }
  return { frontmatter, body: m[2].trim() };
}
